version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd book/frontend
      - npm ci

  build:
    commands:
      - npm run build

artifacts:
  base-directory: book/frontend/out
  files:
    - '**/*'
